//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "RBBaseViewControllerLifecycleObserver-Protocol.h"
#import "RBFeatureRequiredParameters-Protocol.h"

@class NSPointerArray, NSString, UIImage, UILabel;

@interface RBBaseViewController : UIViewController <RBFeatureRequiredParameters, RBBaseViewControllerLifecycleObserver>
{
    _Bool _showNavigationIcons;
    _Bool _addSearchListeners;
    NSString *_accessibilityIdentifier;
    NSPointerArray *_lifecycleObservers;
    NSString *_screenEnumName;
    UIImage *_rbxImage;
    UIImage *_rbxImageDown;
    long long _resultTypeForSearch;
    UILabel *_ageLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *ageLabel; // @synthesize ageLabel=_ageLabel;
@property(nonatomic) long long resultTypeForSearch; // @synthesize resultTypeForSearch=_resultTypeForSearch;
@property(retain, nonatomic) UIImage *rbxImageDown; // @synthesize rbxImageDown=_rbxImageDown;
@property(retain, nonatomic) UIImage *rbxImage; // @synthesize rbxImage=_rbxImage;
@property(retain, nonatomic) NSString *screenEnumName; // @synthesize screenEnumName=_screenEnumName;
@property(nonatomic) _Bool addSearchListeners; // @synthesize addSearchListeners=_addSearchListeners;
@property(retain, nonatomic) NSPointerArray *lifecycleObservers; // @synthesize lifecycleObservers=_lifecycleObservers;
@property(nonatomic) _Bool showNavigationIcons; // @synthesize showNavigationIcons=_showNavigationIcons;
@property(retain, nonatomic) NSString *accessibilityIdentifier; // @synthesize accessibilityIdentifier=_accessibilityIdentifier;
- (void)updateAgeLabelIfNeeded;
- (_Bool)needToShowAgeLabel;
- (id)createOriginalTitleLabel;
- (id)createAgeLabel;
- (id)versionDescription;
- (id)versionLabelWithFrame:(struct CGRect)arg1;
- (void)reloadContent;
- (_Bool)shouldAnimateReloadContent;
- (_Bool)shouldHideNavigationController;
- (void)setViewControllerSelected:(id)arg1 withParams:(id)arg2;
- (void)displayGroupSearchResults:(id)arg1;
- (void)displayCatalogSearchResults:(id)arg1;
- (void)displayUserSearchResults:(id)arg1;
- (void)displaySelectedUser:(id)arg1;
- (void)displayGameSearchResults:(id)arg1;
- (void)pushGameDetailWithURL:(id)arg1;
- (void)pushProfileControllerWithURL:(id)arg1;
- (void)pushProfileControllerWithUserID:(id)arg1;
- (void)pushWebControllerwithURL:(id)arg1 andTitle:(id)arg2;
- (void)pushWebControllerwithURL:(id)arg1;
- (void)handleWebRequestWithPopout:(id)arg1;
- (long long)handleWebRequest:(id)arg1 updateUI:(_Bool)arg2;
- (void)didPressNotificationStream;
- (void)openBuyRobuxPopover;
- (void)didPressBuyRobux;
- (void)updateSearchIconWithSearchType:(long long)arg1;
- (void)removeSearchIcon;
- (void)addSearchIconWithSearchType:(long long)arg1;
- (id)makeRobuxIcon;
- (id)navigationIconsPhone;
- (id)navigationIconsTablet;
- (id)navigationIcons;
- (void)configureNavigationIcons;
- (void)removeLifecycleObsever:(id)arg1;
- (void)addLifecycleObserver:(id)arg1;
@property(readonly, nonatomic) _Bool listensToBuyRobuxPopoverLifecycle;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)getAccessibilityIdentifier;
- (void)initBaseDefaults;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

