//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RBBaseViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "RBConnectivityDelegate-Protocol.h"
#import "RBFeatureRequiredParameters-Protocol.h"
#import "RBFeatureUpdaterDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WKHTTPCookieStoreObserver-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKScriptMessageHandler-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class MBProgressHUD, NSDate, NSString, RBNoConnectivityView, UIButton, UILabel, UIRefreshControl, UISearchBar, UIView;
@protocol RBWebViewStateDelegate, RBXWebViewProtocol><RBHybridWebViewProtocol;

@interface RBMobileWebViewController : RBBaseViewController <UIScrollViewDelegate, UIAlertViewDelegate, WKUIDelegate, WKNavigationDelegate, WKScriptMessageHandler, RBConnectivityDelegate, RBFeatureRequiredParameters, WKHTTPCookieStoreObserver, RBFeatureUpdaterDelegate, MFMailComposeViewControllerDelegate>
{
    _Bool _showNavButtons;
    _Bool _isPopover;
    _Bool _isJavascriptHybridManagedByLuaTemp;
    _Bool _showWholeScreen;
    _Bool _didReceiveMemoryWarningFlag;
    _Bool _loadingInProgress;
    int _placeID;
    UIView<RBXWebViewProtocol><RBHybridWebViewProtocol> *_rbxWebView;
    NSString *_url;
    NSString *_purchasingContext;
    MBProgressHUD *_spinner;
    id <RBWebViewStateDelegate> _webViewStateDelegate;
    UISearchBar *_searchBar;
    UIButton *_backButton;
    RBNoConnectivityView *_connectivityErrorView;
    UIRefreshControl *_refreshControl;
    NSDate *_dhv2InjectingTime;
    UIView *_lowerTopBar;
    UIButton *_lowerBackButton;
    UILabel *_lowerTitleLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *lowerTitleLabel; // @synthesize lowerTitleLabel=_lowerTitleLabel;
@property(retain, nonatomic) UIButton *lowerBackButton; // @synthesize lowerBackButton=_lowerBackButton;
@property(retain, nonatomic) UIView *lowerTopBar; // @synthesize lowerTopBar=_lowerTopBar;
@property(retain, nonatomic) NSDate *dhv2InjectingTime; // @synthesize dhv2InjectingTime=_dhv2InjectingTime;
@property(nonatomic) _Bool loadingInProgress; // @synthesize loadingInProgress=_loadingInProgress;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(nonatomic) _Bool didReceiveMemoryWarningFlag; // @synthesize didReceiveMemoryWarningFlag=_didReceiveMemoryWarningFlag;
@property(retain, nonatomic) RBNoConnectivityView *connectivityErrorView; // @synthesize connectivityErrorView=_connectivityErrorView;
@property(nonatomic) _Bool showWholeScreen; // @synthesize showWholeScreen=_showWholeScreen;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) _Bool isJavascriptHybridManagedByLuaTemp; // @synthesize isJavascriptHybridManagedByLuaTemp=_isJavascriptHybridManagedByLuaTemp;
@property(retain, nonatomic) id <RBWebViewStateDelegate> webViewStateDelegate; // @synthesize webViewStateDelegate=_webViewStateDelegate;
@property(retain, nonatomic) MBProgressHUD *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) NSString *purchasingContext; // @synthesize purchasingContext=_purchasingContext;
@property(nonatomic) int placeID; // @synthesize placeID=_placeID;
@property(nonatomic) _Bool isPopover; // @synthesize isPopover=_isPopover;
@property(nonatomic) _Bool showNavButtons; // @synthesize showNavButtons=_showNavButtons;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) UIView<RBXWebViewProtocol><RBHybridWebViewProtocol> *rbxWebView; // @synthesize rbxWebView=_rbxWebView;
- (void)cookiesDidChangeInCookieStore:(id)arg1;
- (void)presentMailComposerWithEmailAddress:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)updateFeatureWithOptions:(id)arg1;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (_Bool)shouldStartDecidePolicy:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)reportTotalStartupTime;
- (void)updateNavButtonsState;
- (_Bool)shouldStartNavigationActionWithRequest:(id)arg1 navigationType:(long long)arg2;
- (_Bool)isSupportedRobuxUrl:(id)arg1;
- (_Bool)shouldNavigateToLink:(id)arg1 navigationType:(long long)arg2;
- (void)setToShowWholeScreen:(_Bool)arg1;
- (void)refreshBackgroundColorOfWebView:(id)arg1;
- (id)requestWithCookies:(id)arg1;
- (void)reachabilityDidChange:(id)arg1;
- (void)hideConnectivityError;
- (void)showConnectivityError;
- (void)reloadWebPage;
- (void)reloadContent;
- (void)refreshContent;
- (void)loadURL:(id)arg1 screenURL:(_Bool)arg2 updateUI:(_Bool)arg3;
- (void)loadURL:(id)arg1 screenURL:(_Bool)arg2;
- (void)loadURL:(id)arg1;
- (void)setUrl:(id)arg1 updateUI:(_Bool)arg2;
- (void)cleanupWebView;
- (void)dealloc;
- (_Bool)isWebViewControllerBeingDismissed;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)needToRecreateWebView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)closeWithCompletion:(CDUnknownBlockType)arg1;
- (void)didPressClose;
- (void)lowerTopBarClosePressed;
- (void)retry;
- (void)createRefreshControlForWebView;
- (_Bool)isRetryInProgress;
- (void)viewDidLoad;
- (void)addCloseButton:(SEL)arg1;
- (void)viewWillLayoutSubviews;
- (void)didPressBack;
- (void)didReceiveShareGameToChat:(id)arg1;
- (void)setAccessibilityForView;
- (void)injectCookie:(id)arg1 withValue:(id)arg2 forDomain:(id)arg3;
- (void)setViewTitle:(id)arg1;
- (void)addLowerTopBar;
- (void)updateLowerTopBar;
- (void)createRbxWebView;
- (void)createLowerTopBar;
- (void)createConstraints;
- (void)createSpinner;
- (void)createBackButton;
- (void)initializeViews;
- (void)subscribeForNotifications;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithNavButtons:(_Bool)arg1;
- (id)init;
- (void)initDefaults;

// Remaining properties
@property(retain, nonatomic) NSString *accessibilityIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

