//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RBMobileWebViewController.h"

@interface RBWebHomeViewController : RBMobileWebViewController
{
}

- (void)reloadWebpageForUpdatedContent;
- (void)dealloc;
- (void)viewDidLoad;

@end

